config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)' do
    root :to => 'weeks#index'
    resources :weeks, only: [:index, :show, :create, :destroy]
    get 'day/:id', to: 'days#show', as: :day
  end

  patch 'days/:id/toggle_wr', to: 'days#toggle_wr', as: :days_toggle_wr
  patch 'ods/:id/toggle_o', to: 'ods#toggle_o', as: :ods_toggle_o
  patch 'ods/:id/toggle_d', to: 'ods#toggle_d', as: :ods_toggle_d

end

app/models/day.rb
# Day Resource Model
class Day < ResourceBase

  # Text value for boolean
  WR_TEXT_TRUE = I18n.t('Well')
  # Text value for boolean
  WR_TEXT_FALSE = I18n.t('Poor')
  
  # Twitter Bootstrap Button Style Class
  WR_STYLE_TRUE = 'btn-success'
  # Twitter Bootstrap Button Style Class
  WR_STYLE_FALSE = 'btn-danger'

  # Style class
  IS_TODAY_STYLE = 'pnpC-is-today'

  # returns format date string for date
  def str_date
    date_date = date.to_date
    I18n.l(date_date, format: :m_d_wd)
  end

  # returns string for well_registered boolean
  def str_wr
    well_registered ? WR_TEXT_TRUE : WR_TEXT_FALSE
  end

  # returns Style class for well_registered boolean
  def str_wr_TwbsBtnStyleClass
    well_registered ? WR_STYLE_TRUE : WR_STYLE_FALSE
  end

  # returns Style for current day
  # used in Week show (table of days)
  def str_isTodayClass
    (date == Date.today.to_s) ? IS_TODAY_STYLE : ''
  end

end

app/models/od.rb
# Od Resource Model
class Od < ResourceBase

  # Text value for boolean
  OD_TEXT_TRUE = 'ON'
  # Text value for boolean
  OD_TEXT_FALSE = 'OFF'
  
  # Twitter Bootstrap Button Style Class
  OD_STYLE_TRUE = 'btn-success'
  # Twitter Bootstrap Button Style Class
  OD_STYLE_FALSE = 'btn-default'

  # returns text for o boolean
  def str_o_enabled
    str_od_enabled(o)
  end

  # returns text for d boolean
  def str_d_enabled
    str_od_enabled(d)
  end

  # returns text value for o or d boolean
  def str_od_enabled(od)
    od ? OD_TEXT_TRUE : OD_TEXT_FALSE
  end

  # returns Twitter Bootstrap style for o boolean
  def str_o_TwbsBtnStyleClass
    str_od_TwbsBtnStyleClass(o)
  end

  # returns Twitter Bootstrap style for o boolean
  def str_d_TwbsBtnStyleClass
    str_od_TwbsBtnStyleClass(d)
  end

  # returns Twitter Bootstrap style for o or d booleans
  def str_od_TwbsBtnStyleClass(od)
    od ? OD_STYLE_TRUE : OD_STYLE_FALSE
  end

end

app/models/resource_base.rb
# Resource Base Model
class ResourceBase < ActiveResource::Base
  self.site = "http://localhost:3000"
end

app/models/week.rb
# Week Resource Model
class Week < ResourceBase

  # Style class for current week
  IS_CURRENT_WEEK_STYLE = 'pnpC-is-current-week'

  # returns localized date for firstDay string
  def str_firstDay
    date_firstDay = firstDay.to_date
    I18n.l(date_firstDay, format: :m_d)
  end

  # returns rounded float for oAVG string
  def str_oAVG
    float_firstDay = oAVG.to_f
    float_firstDay.round(1)
  end

  # returns rounded float for dAVG string
  def str_dAVG
    float_firstDay = dAVG.to_f
    float_firstDay.round(1)
  end

  # returns IS_CURRENT_WEEK_STYLE for current week  
  # used in Weeks index
  def str_isCurrentWeekClass
    currentWeekFirstDay = Date.today.beginning_of_week(:sunday)
    (firstDay.to_s == currentWeekFirstDay.to_s) ? IS_CURRENT_WEEK_STYLE : ''
  end

end

app/controllers/application_controller.rb
# Application Controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :set_locale
  
  # sets locale from url param
  def set_locale
    if ( ['en','es'].include? params[:locale] ) 
      I18n.locale = params[:locale]
    else
      I18n.locale = I18n.default_locale
    end
  end

end

app/controllers/days_controller.rb
# Days Controller
class DaysController < ApplicationController
  before_action :set_day, only: [:show]
  
  # GET /days/1
  def show
    @day.ods = Od.find(:all, :from => "/days/#{@day.id}/ods.json")
  end

  # PATCH /days/1/toggle_wr
  def toggle_wr
    @week = Day.patch("#{params[:id]}/toggle_wr")
    respond_to do |format|
      format.json { render inline: @week.body.html_safe, layout: false, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

end

app/controllers/ods_controller.rb
# Ods Controller
class OdsController < ApplicationController
  
  # PATCH /ods/1/toggle_o
  def toggle_o
    Od.patch("#{params[:id]}/toggle_o")
    render :nothing => true
  end

  # PATCH /ods/1/toggle_d
  def toggle_d
    Od.patch("#{params[:id]}/toggle_d")
    render :nothing => true
  end

end

app/controllers/weeks_controller.rb
# Weeks Controller
class WeeksController < ApplicationController
  before_action :set_week, only: [:show, :destroy]

  # GET /weeks
  def index
    @weeks = Week.all
    @str_today = I18n.l(Date.today, format: :m_d_wd)

    lastWeek = @weeks.last
    date_newWeekFirstDay = lastWeek.firstDay.to_date + 1.week
    @str_newWeekFirstDay = date_newWeekFirstDay.strftime('%b %e')
  end
  
  # GET /weeks/1
  def show
    @week.days = Day.find(:all, :from => "/weeks/#{@week.id}/days.json")
  end

  # DELETE /weeks/1
  def destroy
    @week.destroy
    redirect_to weeks_url, notice: 'Week was successfully destroyed.'
  end

  # POST /weeks.json
  def create
    @week = Week.new
    @week.save
    redirect_to @week, notice: 'Week was successfully created.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_week
      @week = Week.find(params[:id])
    end

end

app/helpers/application_helper.rb
# Application Helper
module ApplicationHelper
  # sets title for pages
  def title(page_title)
    content_for(:title) { page_title }
  end
  # sets classes for body HTML tag
  def body_classes(page_body_classes)
    content_for(:body_classes) { page_body_classes }
  end
end

app/views/days/_day.html.erb
    <tr id="pnpC-day-id-<%= day.id %>">
      <td class="<%= day.str_isTodayClass %>"><%= link_to day.str_date, day, :class => 'btn btn-default' %>
      <td><%= day.oTotal %></td>
      <td><%= day.dTotal %></td>
      <td><%= link_to day.str_wr, days_toggle_wr_path(day.id), :method => :patch, :remote => true, :class=>"pnpC-day-wr-btn btn " + day.str_wr_TwbsBtnStyleClass %></td>
    </tr>

app/views/days/show.html.erb
<% title "Day (#{@day.str_date})" %>
<% body_classes "pnpC-day pnpC-show" %>

<h1><%= yield :title %></h1>

<p>
  oTotal: <span id="pnpC-oTotal"><%= @day.oTotal %></span>, dTotal: <span id="pnpC-dTotal"><%= @day.dTotal %></span>
</p>

<div class="pnpC-controls">
  <%= link_to t('Back'), week_path(@day.week_id), :class=>"btn btn-primary" %>
</div>

<p id="notice"><%= notice %></p>

<table id="pnpC-ods-table" class="table">
  <thead>
    <tr>
      <th>Timekey</th>
      <th>O</th>
      <th>D</th>
    </tr>
  </thead>
  <tbody>
    <%= render @day.ods %>
  </tbody>
</table>

<div class="pnpC-clearer"></div>

<div class="pnpC-controls">
  <%= link_to t('Back'), week_path(@day.week_id), :class=>"btn btn-small btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) + " | PnP Client" : "PnP Client" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= content_for?(:body_classes) ? "pnpC " + yield(:body_classes) : "pnpC" %>">

<div class="pnpC-container col-xs-12 col-sm-5 col-md-5">


<div class="pnpC-content">
<%= yield %>
</div>


<div class="pnpC-clearer"></div>


<div class="pnpC-footer">
  <div class="pnpC-credits">P n' P app</div>
  <div class="pnpC-tagline"><%= t('tagline') %></div>
</div>


</div>

</body>
</html>

app/views/ods/_od.html.erb
    <tr>
      <td class="pnpC-timekey"><%= od.timekey %></td>
      <td><%= link_to od.str_o_enabled, ods_toggle_o_path(od.id), :method => :patch, :remote => true, :class=>"pnpC-btn-o-toggle btn " + od.str_o_TwbsBtnStyleClass %></td>
      <td><%= link_to od.str_d_enabled, ods_toggle_d_path(od.id), :method => :patch, :remote => true, :class=>"pnpC-btn-d-toggle btn " + od.str_o_TwbsBtnStyleClass %></td>
    </tr>

app/views/weeks/_week.html.erb
      <tr id="pnpC-week-id-<%= week.id %>">
        <td class="<%= week.str_isCurrentWeekClass %>"><%= link_to week.str_firstDay, week, :class => 'btn btn-default' %></td>
        <td><%= week.str_oAVG %></td>
        <td><%= week.str_dAVG %></td>
        <td><%= link_to t('Destroy'), week, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/weeks/index.html.erb
<% title t('Weeks') %>
<% body_classes "pnpC-week pnpC-index" %>
<h1><%= yield :title %></h1>

<p id="notice"><%= notice %></p>

<div class="pnpC-date"><%= t('today_is') + ' ' + @str_today %></div>

<table id="pnpC-weeks-table" class="table">
  <thead>
    <tr>
      <th><%= t 'first_day' %></th>
      <th><%= t 'oAVG' %></th>
      <th><%= t 'dAVG' %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @weeks %>
  </tbody>
</table>

<div class="pnpC-create-new-week">
  <%= link_to "New Week (#{@str_newWeekFirstDay})", weeks_path, method: :post, :class => 'btn btn-primary' %>
</div>

app/views/weeks/show.html.erb
<% title "Week (#{@week.str_firstDay})" %>
<% body_classes "pnpC-week pnpC-show" %>

<h1><%= yield :title %></h1>

<p>
  <strong><%= t('Comment')+':' %></strong>
  <%= @week.comment %>
  <%= t('Edit') %>
</p>

<div class="pnpC-controls">
  <%= link_to t('Back'), weeks_path, :class => 'btn btn-primary' %>
</div>

<p id="notice"><%= notice %></p>

<table id="pnpC-stats-table" class="table">
  <thead>
    <tr>
      <th><%= t('Stats') %></th>
      <th>O</th>
      <th>D</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= t('AVG') %></td>
      <td id="pnpC-oAVG"><%= @week.str_oAVG %></td>
      <td id="pnpC-dAVG"><%= @week.str_dAVG %></td>
    </tr>
    <tr>
      <td>MAX</td>
      <td id="pnpC-oMAX"><%= @week.oMAX %></td>
      <td id="pnpC-dMAX"><%= @week.dMAX %></td>
    </tr>
    <tr>
      <td>MIN</td>
      <td id="pnpC-oMIN"><%= @week.oMIN %></td>
      <td id="pnpC-dMIN"><%= @week.dMIN %></td>
    </tr>
  </tbody>
</table>

<table id="pnpC-days-table" class="table">
  <thead>
    <tr>
      <th><%= t('Day') %></th>
      <th>O</th>
      <th>D</th>
      <th><%= t('well_registered') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @week.days %>
  </tbody>
</table>

<div class="pnpC-controls">
  <%= link_to t('Back'), weeks_path, :class => 'btn btn-primary' %>
</div>